### ISSUE TITLE
$websiteKey must not be accessed before initialization

### ISSUE THREAD

**Issue by janhenckens** [born05/craft-commerce-buckaroo#2]
Testing out this plugin for a potential feature in a project and I'm getting this error when trying to add a gateway:

`Error: Typed property born05\commerce\buckaroo\gateways\CreditCardGateway::$websiteKey must not be accessed before initialization in /var/www/html/vendor/craftcms/cms/src/helpers/Template.php:118`

I'm running:
Craft 4.5.1
Commerce 4.2.11
PHP 8.1.21

**Comment by roelvanhintum** [comment]
Should be fixed with 2.1.2

**Comment by janhenckens** [comment]
Thanks @roelvanhintum!
